# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmpitcpp <- function(arr) {
    .Call('_transgeneR_cmpitcpp', PACKAGE = 'transgeneR', arr)
}

clustercpp <- function(arr) {
    .Call('_transgeneR_clustercpp', PACKAGE = 'transgeneR', arr)
}

findhomo <- function(dir, para) {
    invisible(.Call('_transgeneR_findhomo', PACKAGE = 'transgeneR', dir, para))
}

assignreads <- function(ipt, para) {
    invisible(.Call('_transgeneR_assignreads', PACKAGE = 'transgeneR', ipt, para))
}

reassignreads <- function(dir, dist) {
    invisible(.Call('_transgeneR_reassignreads', PACKAGE = 'transgeneR', dir, dist))
}

